spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bancoPA}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:eldevborges}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Lf19092019f-}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret = ${"minha-chave-jwt"}
jwt.expiration = 3600000
spring.mvc.pathmath.use-suffix-pattern = false
server.port = 8080